import type { ResearchFocus, TechBranch, Technology } from "../types";

export const TECH_BRANCHES: Record<
  TechBranch,
  { name: string; short: string; description: string }
> = {
  graphics: {
    name: "Grafik",
    short: "GFX",
    description: "Sprites, 3D und Licht. Stärkt Qualität und deine Engine.",
  },
  gameplay: {
    name: "Gameplay & KI",
    short: "KI",
    description: "Systeme, Werkzeuge und Gegner. Starke Genre-Boni.",
  },
  audio: {
    name: "Audio",
    short: "SFX",
    description: "Klang, Musik und Stimmen für dichtere Welten.",
  },
  production: {
    name: "Produktion",
    short: "PRD",
    description: "Schneller, günstiger und mit weniger Bugs entwickeln.",
  },
  network: {
    name: "Technik & Online",
    short: "NET",
    description: "Reichweite, Portierungen und ein langer Verkaufsschwanz.",
  },
  business: {
    name: "Business",
    short: "BIZ",
    description: "Marketing, Fans und eine stärkere Forschungsabteilung.",
  },
  programs: {
    name: "Programme",
    short: "∞",
    description: "Wiederholbare Forschung mit steigenden Kosten.",
  },
};

export const TECHNOLOGIES: Technology[] = [
  // Grafik
  {
    id: "sprites",
    name: "Dynamische Sprites",
    category: "graphics",
    tier: 1,
    points: 18,
    cost: 1800,
    days: 12,
    year: 1990,
    standard: 1993,
    requires: [],
    description: "Lebendige Animationen und stärkere visuelle Qualität.",
    effects: { quality: 2, engine: 1, genres: { Action: 1 } },
  },
  {
    id: "parallax",
    name: "Parallax-Scrolling",
    category: "graphics",
    tier: 1,
    points: 22,
    cost: 2200,
    days: 14,
    year: 1990,
    requires: [],
    description: "Mehrere Bildebenen erzeugen Tiefe und Tempo.",
    effects: { genres: { Action: 2, Racing: 2, Adventure: 1 } },
  },
  {
    id: "mode7",
    name: "Pseudo-3D",
    category: "graphics",
    tier: 2,
    points: 45,
    cost: 5000,
    days: 22,
    year: 1991,
    standard: 1995,
    requires: ["sprites"],
    description: "Skalierte Ebenen simulieren Räume – perfekt für Rennstrecken.",
    effects: { quality: 1, engine: 1, genres: { Racing: 3, Sport: 2 } },
  },
  {
    id: "3d",
    name: "3D-Rendering",
    category: "graphics",
    tier: 3,
    points: 60,
    cost: 9000,
    days: 30,
    year: 1993,
    standard: 1997,
    requires: ["mode7"],
    description: "Der nächste Schritt in eine neue Dimension.",
    effects: { quality: 3, engine: 1, genres: { Action: 2, Racing: 2 } },
  },
  {
    id: "textures",
    name: "Texturfilterung",
    category: "graphics",
    tier: 3,
    points: 110,
    cost: 16000,
    days: 34,
    year: 1995,
    standard: 1999,
    requires: ["3d"],
    description: "Glatte Oberflächen statt Pixelbrei auf nahen Wänden.",
    effects: { quality: 2, engine: 1, genres: { Horror: 2 } },
  },
  {
    id: "lighting",
    name: "Dynamisches Licht",
    category: "graphics",
    tier: 4,
    points: 170,
    cost: 28000,
    days: 42,
    year: 1998,
    standard: 2002,
    requires: ["textures"],
    description: "Schatten, Fackeln und Mündungsfeuer in Echtzeit.",
    effects: { quality: 3, engine: 1, genres: { Horror: 3, Adventure: 1 } },
  },
  {
    id: "shaders",
    name: "Programmierbare Shader",
    category: "graphics",
    tier: 4,
    points: 240,
    cost: 45000,
    days: 50,
    year: 2001,
    standard: 2005,
    requires: ["lighting"],
    description: "Wasser, Glanz und Effekte, die eine Generation definieren.",
    effects: { quality: 4, engine: 1 },
  },
  // Gameplay & KI
  {
    id: "ai",
    name: "Adaptive KI",
    category: "gameplay",
    tier: 1,
    points: 28,
    cost: 2800,
    days: 18,
    year: 1990,
    requires: [],
    description: "Glaubwürdige Gegner und tiefere Spielsysteme.",
    effects: { quality: 1, genres: { Strategie: 3, Action: 1, Sport: 1 } },
  },
  {
    id: "editor",
    name: "Level-Editor",
    category: "gameplay",
    tier: 1,
    points: 24,
    cost: 2400,
    days: 15,
    year: 1990,
    requires: [],
    description: "Designer bauen Level selbst – schneller und verspielter.",
    effects: { speed: 0.03, genres: { Puzzle: 3, Strategie: 1, Adventure: 1 } },
  },
  {
    id: "dialog",
    name: "Dialogbäume",
    category: "gameplay",
    tier: 2,
    points: 40,
    cost: 4200,
    days: 20,
    year: 1991,
    requires: ["editor"],
    description: "Verzweigte Gespräche mit echten Konsequenzen.",
    effects: { genres: { RPG: 4, Adventure: 3 } },
  },
  {
    id: "physics",
    name: "Physik-Simulation",
    category: "gameplay",
    tier: 2,
    points: 55,
    cost: 6000,
    days: 24,
    year: 1992,
    standard: 1998,
    requires: ["ai"],
    description: "Gewicht, Reibung und Kollisionen, die sich echt anfühlen.",
    effects: { genres: { Racing: 3, Sport: 3, Simulation: 2 } },
  },
  {
    id: "procgen",
    name: "Prozedurale Welten",
    category: "gameplay",
    tier: 3,
    points: 100,
    cost: 14000,
    days: 32,
    year: 1995,
    requires: ["editor", "ai"],
    description: "Algorithmen erzeugen riesige, abwechslungsreiche Welten.",
    effects: { quality: 1, genres: { RPG: 2, Strategie: 2, Simulation: 2 } },
  },
  {
    id: "emergent",
    name: "Emergente KI",
    category: "gameplay",
    tier: 4,
    points: 180,
    cost: 30000,
    days: 45,
    year: 1999,
    requires: ["procgen", "physics"],
    description: "Figuren mit eigenen Zielen erzeugen unvergessliche Momente.",
    effects: { quality: 3, genres: { Strategie: 2, Simulation: 2 } },
  },
  // Audio
  {
    id: "audio",
    name: "Mehrkanal-Audio",
    category: "audio",
    tier: 1,
    points: 20,
    cost: 2000,
    days: 14,
    year: 1990,
    standard: 1993,
    requires: [],
    description: "Atmosphäre, die in Erinnerung bleibt.",
    effects: { quality: 1, engine: 1, genres: { Horror: 2 } },
  },
  {
    id: "synth",
    name: "Synthesizer-Soundtracks",
    category: "audio",
    tier: 2,
    points: 38,
    cost: 4000,
    days: 18,
    year: 1991,
    requires: ["audio"],
    description: "Ohrwürmer, die Spieler noch Jahre später summen.",
    effects: { quality: 1, hype: 2, genres: { Adventure: 2, RPG: 1, Racing: 1 } },
  },
  {
    id: "voice",
    name: "Sprachausgabe",
    category: "audio",
    tier: 3,
    points: 90,
    cost: 12000,
    days: 30,
    year: 1994,
    standard: 1999,
    requires: ["synth"],
    description: "Vertonte Figuren lassen Geschichten lebendig werden.",
    effects: { quality: 1, genres: { RPG: 3, Adventure: 3, Horror: 1 } },
  },
  {
    id: "surround",
    name: "3D-Raumklang",
    category: "audio",
    tier: 4,
    points: 150,
    cost: 24000,
    days: 38,
    year: 1998,
    requires: ["voice"],
    description: "Schritte hinter dir. Atem neben dir. Gänsehaut garantiert.",
    effects: { quality: 2, engine: 1, genres: { Horror: 3, Action: 1 } },
  },
  // Produktion
  {
    id: "pipeline",
    name: "Asset-Pipeline",
    category: "production",
    tier: 1,
    points: 30,
    cost: 3500,
    days: 20,
    year: 1990,
    requires: [],
    description: "Verkürzt die Entwicklungsdauer zukünftiger Projekte.",
    effects: { speed: 0.15 },
  },
  {
    id: "vcs",
    name: "Versionskontrolle",
    category: "production",
    tier: 1,
    points: 20,
    cost: 1600,
    days: 10,
    year: 1990,
    requires: [],
    description: "Kein überschriebener Code mehr. Deutlich weniger Fehler.",
    effects: { bugs: 0.15 },
  },
  {
    id: "qa",
    name: "Automatisierte Tests",
    category: "production",
    tier: 2,
    points: 50,
    cost: 5500,
    days: 22,
    year: 1992,
    requires: ["vcs"],
    description: "Testläufe über Nacht finden Bugs, bevor Kritiker sie finden.",
    effects: { bugs: 0.2, quality: 1 },
  },
  {
    id: "tools",
    name: "Interne Werkzeuge",
    category: "production",
    tier: 2,
    points: 60,
    cost: 7000,
    days: 24,
    year: 1993,
    requires: ["pipeline"],
    description: "Eigene Editoren sparen jeden Tag wertvolle Stunden.",
    effects: { speed: 0.06, cost: 0.05 },
  },
  {
    id: "agile",
    name: "Agile Produktion",
    category: "production",
    tier: 3,
    points: 110,
    cost: 15000,
    days: 32,
    year: 1996,
    requires: ["tools", "qa"],
    description: "Kurze Iterationen, früheres Feedback, weniger Sackgassen.",
    effects: { speed: 0.08, bugs: 0.1 },
  },
  {
    id: "outsourcing",
    name: "Globales Outsourcing",
    category: "production",
    tier: 4,
    points: 160,
    cost: 26000,
    days: 36,
    year: 2000,
    requires: ["agile"],
    description: "Partnerstudios übernehmen Assets rund um die Uhr.",
    effects: { cost: 0.15, speed: 0.05 },
  },
  // Technik & Online
  {
    id: "compression",
    name: "Datenkompression",
    category: "network",
    tier: 1,
    points: 22,
    cost: 2000,
    days: 12,
    year: 1990,
    requires: [],
    description: "Weniger Disketten pro Spiel senkt Kosten und Preise.",
    effects: { cost: 0.04, sales: 0.03 },
  },
  {
    id: "porting",
    name: "Portierungs-Layer",
    category: "network",
    tier: 2,
    points: 48,
    cost: 5000,
    days: 20,
    year: 1992,
    requires: ["compression"],
    description: "Ein Code, viele Plattformen. Mehr Reichweite für weniger Geld.",
    effects: { cost: 0.06, sales: 0.04 },
  },
  {
    id: "network",
    name: "Netzwerkspiel",
    category: "network",
    tier: 3,
    points: 80,
    cost: 12000,
    days: 35,
    year: 1995,
    standard: 1999,
    requires: ["compression"],
    description: "Verbindet Spieler und stärkt den Long Tail.",
    effects: {
      longTail: 0.2,
      engine: 1,
      genres: { Action: 2, Strategie: 2, Sport: 1, Racing: 1 },
    },
  },
  {
    id: "online",
    name: "Online-Updates",
    category: "network",
    tier: 4,
    points: 140,
    cost: 22000,
    days: 36,
    year: 1998,
    requires: ["network"],
    description: "Patches erreichen Spieler direkt. Fehler verzeiht man eher.",
    effects: { bugs: 0.15, longTail: 0.15 },
  },
  {
    id: "servers",
    name: "Dedizierte Server",
    category: "network",
    tier: 4,
    points: 200,
    cost: 38000,
    days: 44,
    year: 2001,
    requires: ["online"],
    description: "Eigene Server halten Communities jahrelang am Leben.",
    effects: { longTail: 0.25, fans: 0.15, genres: { RPG: 2, Action: 1 } },
  },
  // Business
  {
    id: "press",
    name: "Pressearbeit",
    category: "business",
    tier: 1,
    points: 16,
    cost: 1500,
    days: 10,
    year: 1990,
    requires: [],
    description: "Gute Kontakte zu Magazinen bringen Spiele früher ins Gespräch.",
    effects: { campaign: 6, hype: 3 },
  },
  {
    id: "market",
    name: "Marktforschung",
    category: "business",
    tier: 1,
    points: 24,
    cost: 2500,
    days: 14,
    year: 1990,
    requires: [],
    description: "Wer seine Käufer kennt, verkauft mehr.",
    effects: { sales: 0.05 },
  },
  {
    id: "rnd",
    name: "Forschungsabteilung",
    category: "business",
    tier: 2,
    points: 35,
    cost: 4500,
    days: 16,
    year: 1991,
    requires: ["market"],
    description: "Feste Strukturen für Wissen: mehr Punkte, schnellere Projekte.",
    effects: { research: 0.2, labSpeed: 0.1 },
  },
  {
    id: "community",
    name: "Community-Management",
    category: "business",
    tier: 2,
    points: 50,
    cost: 6000,
    days: 22,
    year: 1993,
    requires: ["press"],
    description: "Fanclubs, Newsletter und Leserbriefe. Fans bleiben treu.",
    effects: { fans: 0.25, hype: 4 },
  },
  {
    id: "focus",
    name: "Fokusgruppen",
    category: "business",
    tier: 3,
    points: 90,
    cost: 12000,
    days: 28,
    year: 1995,
    requires: ["market", "community"],
    description: "Echte Spieler testen früh und zeigen, was nicht funktioniert.",
    effects: { quality: 2, sales: 0.05 },
  },
  {
    id: "knowledge",
    name: "Wissensdatenbank",
    category: "business",
    tier: 3,
    points: 100,
    cost: 14000,
    days: 30,
    year: 1996,
    requires: ["rnd"],
    description: "Jede Erkenntnis bleibt erhalten und beschleunigt die nächste.",
    effects: { research: 0.25, labSpeed: 0.15 },
  },
  {
    id: "brand",
    name: "Markenstrategie",
    category: "business",
    tier: 4,
    points: 150,
    cost: 26000,
    days: 34,
    year: 1999,
    requires: ["focus"],
    description: "Dein Studioname wird selbst zum Verkaufsargument.",
    effects: { sales: 0.1, fans: 0.2, campaign: 8 },
  },
  // Programme (wiederholbar)
  {
    id: "optimize",
    name: "Engine-Optimierung",
    category: "programs",
    tier: 1,
    points: 40,
    cost: 5000,
    days: 20,
    year: 1990,
    maxLevel: 3,
    requires: ["sprites"],
    description: "Jede Stufe macht dein nächstes Framework stärker.",
    effects: { engine: 1, speed: 0.02 },
  },
  {
    id: "playtests",
    name: "Spielerstudien",
    category: "programs",
    tier: 1,
    points: 35,
    cost: 4000,
    days: 18,
    year: 1990,
    maxLevel: 3,
    requires: ["market"],
    description: "Beobachten, wie Menschen spielen – und daraus lernen.",
    effects: { quality: 1 },
  },
  {
    id: "efficiency",
    name: "Effizienzprogramm",
    category: "programs",
    tier: 1,
    points: 45,
    cost: 6000,
    days: 20,
    year: 1990,
    maxLevel: 4,
    requires: ["pipeline"],
    description: "Prozesse verschlanken: Zeit und Budget sparen.",
    effects: { speed: 0.03, cost: 0.03 },
  },
];

export const LABS = [
  {
    name: "Bastelecke",
    subtitle: "Ein Schreibtisch, viele Ideen.",
    slots: 1,
    speed: 1,
    research: 0,
    cost: 0,
    upkeep: 0,
    office: 0,
  },
  {
    name: "Forschungsraum",
    subtitle: "Zwei Projekte gleichzeitig.",
    slots: 2,
    speed: 1.1,
    research: 0.15,
    cost: 15000,
    upkeep: 450,
    office: 1,
  },
  {
    name: "R&D-Abteilung",
    subtitle: "Schneller forschen, mehr Erkenntnisse.",
    slots: 2,
    speed: 1.25,
    research: 0.3,
    cost: 55000,
    upkeep: 1400,
    office: 2,
  },
  {
    name: "Innovationszentrum",
    subtitle: "Drei Projekte, maximale Geschwindigkeit.",
    slots: 3,
    speed: 1.45,
    research: 0.5,
    cost: 180000,
    upkeep: 3800,
    office: 3,
  },
];

export const RESEARCH_FOCUS: Record<
  ResearchFocus,
  {
    name: string;
    description: string;
    points: number;
    speed: number;
    eureka: number;
    setback: number;
  }
> = {
  fundamental: {
    name: "Grundlagen",
    description: "+30 % Forschungspunkte, aber 15 % langsamere Projekte.",
    points: 1.3,
    speed: 0.85,
    eureka: 0.006,
    setback: 0,
  },
  balanced: {
    name: "Ausgewogen",
    description: "Solide Punkte, solides Tempo, gelegentliche Durchbrüche.",
    points: 1,
    speed: 1,
    eureka: 0.01,
    setback: 0,
  },
  applied: {
    name: "Angewandt",
    description: "Projekte 25 % schneller, aber 20 % weniger Punkte.",
    points: 0.8,
    speed: 1.25,
    eureka: 0.004,
    setback: 0,
  },
  experimental: {
    name: "Experimentell",
    description: "Häufige Durchbrüche (+25 %), aber auch Rückschläge (−15 %).",
    points: 1,
    speed: 1,
    eureka: 0.045,
    setback: 0.02,
  },
};
