import {
  BookOpen,
  Bot,
  Clapperboard,
  ClipboardCheck,
  Coffee,
  Dumbbell,
  Gamepad2,
  GraduationCap,
  HeartHandshake,
  Landmark,
  Lightbulb,
  Megaphone,
  Mic,
  Presentation,
  ScanFace,
  Search,
  Server,
  ServerCog,
  Trophy,
  UtensilsCrossed,
  Wrench,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const FACILITY_ICONS: Record<string, LucideIcon> = {
  coffee: Coffee,
  lounge: Gamepad2,
  library: BookOpen,
  server: Server,
  sound: Mic,
  testlab: ClipboardCheck,
  workshop: Wrench,
  academy: GraduationCap,
  showroom: Presentation,
  canteen: UtensilsCrossed,
  scouting: Search,
  gym: Dumbbell,
  people: HeartHandshake,
  mocap: ScanFace,
  datacenter: ServerCog,
  agency: Megaphone,
  innovation: Lightbulb,
  cinema: Clapperboard,
  arena: Trophy,
  museum: Landmark,
  aicore: Bot,
};
